[build]
builder = "nixpacks"
buildCommand = "npm run build"

[[services]]
name = "web"
startCommand = "npm run web:prod"
healthcheckPath = "/"
healthcheckTimeout = 10
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5

[[services]]
name = "worker"
startCommand = "npm run worker:prod"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5