[build]
builder = "nixpacks"
buildCommand = "yarn build"

[deploy]
name = "web"
startCommand = "yarn start"
healthcheckTimeout = 100

[nixpacks]
# Disable caching for now to avoid build issues
features = []