[build]
builder = "nixpacks"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/api/worker-health"
healthcheckTimeout = 100

[deploy.worker]
dockerfile = "Dockerfile.worker"
startCommand = "yarn worker"
healthcheckPath = ""
healthcheckTimeout = 100 